export const ADD_POST = "PROFILE/ADD-POST";
export const DELETE_POST = "PROFILE/DELETE-POST";
export const SET_USER_PROFILE = "PROFILE/SET-USER-PROFILE";
export const SET_USER_STATUS = "PROFILE/SET-USER-STATUS";