export const FOLLOW_TO_USER = "FOLLOW-TO-USER";
export const UNFOLLOW_FROM_USER = "UNFOLLOW-FROM-USER";
export const SET_USERS = "SET-USERS";
export const SET_TOTAL_USERS_COUNT = "SET-TOTAL-USERS-COUNT";
export const SET_CURRENT_PAGE = "SET-CURRENT-PAGE";
export const TOGGLE_IS_LOADING = "TOGGLE-IS-LOADING";
export const TOGGLE_IS_FOLLOWING_PROGRESS = "TOGGLE-IS-FOLLOWING-PROGRESS";