export const FOLLOW_TO_USER = "USERS/FOLLOW-TO-USER";
export const UNFOLLOW_FROM_USER = "USERS/UNFOLLOW-FROM-USER";
export const SET_USERS = "USERS/SET-USERS";
export const SET_TOTAL_USERS_COUNT = "USERS/SET-TOTAL-USERS-COUNT";
export const SET_CURRENT_PAGE = "USERS/SET-CURRENT-PAGE";
export const TOGGLE_IS_LOADING = "USERS/TOGGLE-IS-LOADING";
export const TOGGLE_IS_FOLLOWING_PROGRESS = "USERS/TOGGLE-IS-FOLLOWING-PROGRESS";